### PR TITLE
Translate contributing.md

### PR DESCRIPTION
**Pull request by aromanarguello**
- Translates CONTRIBUTING.md file to Spanish

### CODE REVIEW

**Comment by aromanarguello** [comment]
@laurosilvacom https://github.com/typescript-cheatsheets/react-typescript-cheatsheet-es/pull/5

**Comment by laurelsilva** [comment]
Nice. But I we need to add the `CONTRIBUTORS.md` page. We can call it `CONTRIBUYENTES` or we can call it`COLABORADORES` but it needs to be the same as [CONTRIBUTORS.md](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/CONTRIBUTORS.md). 

Let's leave the CONTRIBUYENDO.md as it is, for now. 
[CONTRIBUYENDO.md](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet-es/blob/master/CONTRIBUYENDO.md) = [CONTRIBUTING.md](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/CONTRIBUTING.md) ✅

**Comment by aromanarguello** [comment]
got it! to make sure I understood. I should remove my changes from `Contribuyendo.md` (leave it as is with your content) and create a `Colaboradores.md`?

**Comment by laurelsilva** [comment]
Correct! Sorry about the misunderstanding.

**Comment by aromanarguello** [comment]
No worries! will get on it :)

**Comment by aromanarguello** [comment]
@laurosilvacom for the contributors file will we use the all-contributors bot, or will we hard code it?

**Comment by laurelsilva** [comment]
The all-contributors bot. Are able to set it up?

**Comment by aromanarguello** [comment]
I can try 😅I've used in the past. The parent repo uses it, might as well try it out. What do you think?

**Comment by laurelsilva** [comment]
Go for it!

**Comment by aromanarguello** [comment]
Added it, let me know your thoughts. 
Some documentation on how to use: https://allcontributors.org/docs/en/bot/usage for anyone who might be interested

**Pull request merged**
