### PR TITLE
add strong rec for ts playground

### PR DESCRIPTION
**Pull request by aromanarguello**
This PR updates README.md to reflect latest commit on master branch from the `typescript-cheatsheets` repository:
https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/commit/ac018eb0e19f49b90a30fc052c3a6769a2ba1975

### CODE REVIEW

**Comment by aromanarguello** [comment]
@laurosilvacom

**Comment by laurelsilva** [comment]
Thanks @aromanarguello. Good work!

**Comment by swyxio** [comment]
nice! is this automatic?

**Comment by laurelsilva** [comment]
No, I wish. We're just keeping an eye on all the new commits from the main repo.

**Pull request merged**
